export {default as Hero} from './hero/hero'
export {default as Categories} from './categories/categories'
export {default as Directions} from './directions/directions'
export {default as Blog} from './blog/blog'
export {default as Subscribe} from './subscribe/subscribe'
export {default as Reviews} from './reviews/reviews'
